### ISSUE TITLE
ajouter les groupes à la page /profile 

### ISSUE THREAD

**Issue by pciavald** [pciavald/dotbase#34]
la page /profile devrait montrer à quels groupes l'utilisateur appartient, cliquables pour accéder aux détails du groupe en question

**Comment by haniju** [comment]
Check mon beau [lien drive](https://docs.google.com/document/d/1rLvRSt0by53UXxwpuduyPsLfT-A2pThdv7sv2gj9OXE/edit?usp=sharing) :)

**Comment by pciavald** [comment]
par contre là j'ai pas bien compris ton lien drive, tu veux bien le mettre directement en html ?
https://github.com/pciavald/dotbase/blob/dev/client/profile/profile.html
aussi je n'ai pas bien compris ce que c'est que date/messages dans la page profil :)

**Comment by haniju** [comment]
c'est la possibilité de contribution individuelle
