### ISSUE TITLE
nouveau groupe

### ISSUE THREAD

**Issue by pciavald** [pciavald/dotbase#35]

**Comment by haniju** [comment]
[.html](https://drive.google.com/open?id=1578MxdgCOSfouVFoOnBcpB3oz8YLzbmGGiA3aeTkaOM)

**Comment by haniju** [comment]
Est-ce que tu veux que je m'occupe des menus déroulants pour les formulaires ?

**Comment by pciavald** [comment]
J'ai fait la page du drive, je veux bien que tu t'occupes des menus déroulants ! Merci :)
ça se passe là : 
https://github.com/pciavald/dotbase/blob/dev/client/newGroup/newGroup.html
