### ISSUE TITLE
404

### ISSUE THREAD

**Issue by pciavald** [pciavald/dotbase#39]
créer une page 404 not found

**Comment by pciavald** [comment]
need style :) `/notfound`

**Comment by haniju** [comment]
what exactly needs style ?

**Comment by kathiouchka** [comment]
Le HTML du dossier 404 pour error_404.html

**Comment by haniju** [comment]
Okay, merci !
Je n'arrive pas à visualiser la page via base, y a t'il une url ?

**Comment by haniju** [comment]
http://localhost:3000/error_404 ne marche pas
![screen shot 2017-01-08 at 08 31 47](https://cloud.githubusercontent.com/assets/5124498/21748128/f4dd6bb4-d57c-11e6-93b6-7b23b7d1eebc.png)

**Comment by pciavald** [comment]
c'est `/notfound` :)

**Comment by haniju** [comment]
Merci, voila c'est fait :)
