### ISSUE TITLE
page en attente de confirmation d'email

### ISSUE THREAD

**Issue by pciavald** [pciavald/dotbase#43]
créer une page qui dit "votre compte a bien été créé, merci de vérifier votre adresse mail et rentrer le même mot de passe que précédemment sur le lien d'activation"

**Comment by pciavald** [comment]
@kathiouchka tu ppeux intégrer la page comme la 404

**Comment by haniju** [comment]
@kathiouchka  Il y a des noms de classe à changer, ping moi avec l'url quand c'est en ligne :)

**Comment by pciavald** [comment]
La page est intégrée dans `/confirmation`, tu peux la restyler @haniju ?
