### ISSUE TITLE
style groupe cassé

### ISSUE THREAD

**Issue by pciavald** [pciavald/dotbase#44]
ça fonctionnait bien avant que je pull ton CSS :)
au passage c'est bien les projets qui sont sur onlyoffice, tu peux en ajouter un sur la plateforme pour tester

![selection_110](https://cloud.githubusercontent.com/assets/3384097/21702070/a4f9f7ae-d3a9-11e6-813a-19921b73c877.png)

**Comment by haniju** [comment]
Mmm, c'est normal je n'ai pas refactor tout les fichier html !
J'ai encore pas mal de classes à changer (au besoin la liste est dans l'issue "refactoring")
ps : je ne sais pas localiser le code html de l'objet en screenshot ci-dessus

**Comment by pciavald** [comment]
https://github.com/pciavald/dotbase/blob/dev/client/index.html#L68
