### ISSUE TITLE
design profile with onename info

### ISSUE THREAD

**Issue by pciavald** [pciavald/dotbase#49]
info in profile is gathered through onename, you have to fill your onename profile to see the problem

![selection_112](https://cloud.githubusercontent.com/assets/3384097/21726031/3c59700c-d43b-11e6-91ad-1c4a4e61f48f.png)

**Comment by haniju** [comment]
What is the problem exactly ?
Also, my profile page doesn't load the onename profile picture & full names...

**Comment by pciavald** [comment]
mainly the image being too big

**Comment by haniju** [comment]
Actually, before closing, i'd like to test on final version, but my profil picture doesn't show, even after re-login

**Comment by pciavald** [comment]
re-subscribe after `meteor reset` ?
